[package]
name = "ont-haec-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "~0.64.0"

[dependencies]
clap = {version = "~4.1.4", features = ["derive"]}
needletail = "~0.5.0"
lazy_static = "~1.4.0"
itertools = "~0.10.5"
rayon = "~1.7.0"
thread_local = "~1.1.4"
indicatif = {version = "~0.17.2", features = ["rayon"]}
ordered-float = "~3.4.0"
ndarray = "~0.15.6"
ndarray-npy = "~0.8.1"