[package]
name = "ont-haec-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "~0.63.0"

[dependencies]
clap = {version = "~4.0.18", features = ["derive"]}
needletail = "~0.4.1"
lazy_static = "~1.4.0"
itertools = "~0.10.5"